// <auto-generated />
namespace DUE_Mernokinfo_Bot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreatData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatData));
        
        string IMigrationMetadata.Id
        {
            get { return "201806241926384_CreatData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
